<?php

return [
    'ABCD111' => [
        'State' => 'ON',
        'Plate' => 'ABCD111',
        'VehYear' => 2004,
        'VehMake' => 'BMW',
        'VehModel' => '530i',
        'OwnerName' => 'John Smith',
        'OwnerAddress1' => '300 Delore Road',
        'OwnerAddress2' => '',
        'OwnerCity' => 'Toronto',
        'OwnerState' => 'ON',
        'OwnerZIP' => 'M5M 2B6',
    ],
    '123ABC' => [
        'State' => 'GA',
        'Plate' => '123ABC',
        'VehYear' => 2008,
        'VehMake' => 'AUDI',
        'VehModel' => 'A7',
        'OwnerName' => 'Chris Namen',
        'OwnerAddress1' => '2300 Ring Road',
        'OwnerAddress2' => '',
        'OwnerCity' => 'Atlanta',
        'OwnerState' => 'GA',
        'OwnerZIP' => '30987',
    ],
    'RRE330' => [
        'State' => 'GA',
        'Plate' => 'RRE330',
        'VehYear' => 1999,
        'VehMake' => 'GM',
        'VehModel' => 'Yukon',
        'OwnerName' => 'Bubba Smith',
        'OwnerAddress1' => '300 Peachtree Blvd',
        'OwnerAddress2' => 'Apt. 1122',
        'OwnerCity' => 'Atlanta',
        'OwnerState' => 'GA',
        'OwnerZIP' => '30254-4524',
    ],
    'AABC23' => [
        'State' => 'GA',
        'Plate' => 'AABC23',
        'VehYear' => 2001,
        'VehMake' => 'FORD',
        'VehModel' => 'F-150',
        'OwnerName' => 'Yanni Minken',
        'OwnerAddress1' => '301 South Padre Blvd',
        'OwnerAddress2' => 'Apt 2001',
        'OwnerCity' => 'Atlanta',
        'OwnerState' => 'GA',
        'OwnerZIP' => '30521',
    ],
];